addons:
  firefox: "34.0.5"
install:
  - npm install -g npm@2
  - npm install
  - npm install coveralls
  - ./node_modules/protractor/bin/webdriver-manager update
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - nohup bash -c "./node_modules/protractor/bin/webdriver-manager start 2>&1 &"
script:
  - gulp test
  - cat ./coverage/lcov.info | ./bin/coveralls.js --verbose
