before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - ./node_modules/protractor/bin/webdriver-manager update
  - ./node_modules/protractor/bin/webdriver-manager start
  - sleep 5
install:
  - npm install
script:
  - gulp test
