before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - nohup bash -c "./nodemodules/protractor/bin/webdriver-manager start 2>&1 &"
  - sleep 5
install:
  - npm install
script:
  - gulp test
